name: CI

on:
  push:
    branches: [ UT_Changes ]
  pull_request:
    branches: ["UT_Changes"]
  
jobs:
  build-up-cpp:
    name: Build up-cpp
    runs-on: ubuntu-latest
    env:
      UP_CPP_Repo: https://github.com/eclipse-uprotocol/up-cpp.git
      UP_CPP_Cache_PFX: up-cpp-conan2
    outputs:
      UP_CPP_Cache: ${{ env.UP_CPP_Cache_PFX }}-${{ steps.up-cpp-head.outputs.UP_CPP_HEAD }}

    steps:
      - name: Check remote head hash
        id: up-cpp-head
        shell: bash
        run: '{ echo -n "UP_CPP_HEAD="; git ls-remote "$UP_CPP_Repo" HEAD | cut -f1; } | tee -a "$GITHUB_OUTPUT"'

      - name: Cache conan artifacts
        id: cache-conan2
        uses: actions/cache@v4
        with:
          key: ${{ env.UP_CPP_Cache_PFX }}-${{ steps.up-cpp-head.outputs.UP_CPP_HEAD }}
          path: |
            ~/.conan2

      - name: Install Conan
        if: ${{ steps.cache-conan2.outputs.cache-hit != 'true' }}
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Create default Conan profile
        if: ${{ steps.cache-conan2.outputs.cache-hit != 'true' }}
        run: conan profile detect

      # NOTE: Checks out the head revision we found using ls-remote above
      #       to avoid race conditions resulting in mismatch between cache
      #       and contents of repo.
      - name: Clone up-cpp repo
        if: ${{ steps.cache-conan2.outputs.cache-hit != 'true' }}
        shell: bash
        env:
          UP_CPP_HEAD: ${{ steps.up-cpp-head.outputs.UP_CPP_HEAD }}
        run: |
          git clone "$UP_CPP_Repo"
          cd up-cpp && git checkout v0.1.2-dev
          git submodule update --init --recursive

      - name: Create up-cpp Conan package
        if: ${{ steps.cache-conan2.outputs.cache-hit != 'true' }}
        shell: bash
        run: |
          cd up-cpp
          conan create . --build=missing

      - name: Clean up conan build files
        if: ${{ steps.cache-conan2.outputs.cache-hit != 'true' }}
        run: conan cache clean '*'
        
  build-vsomeip:
    name: Build vsomeip
    runs-on: ubuntu-latest
    env:
      vsomeip_Repo: https://github.com/COVESA/vsomeip.git
      vsomeip_Tag: 3.4.10
      vsomeip_Cache_PFX: vsomeip-conan2
    outputs:
      vsomeip_Cache: ${{ env.vsomeip_Cache_PFX }}-${{ steps.vsomeip-head.outputs.vsomeip_HEAD }}

    steps:
      - name: Check remote head hash
        id: vsomeip-head
        shell: bash
        run: '{ echo -n "vsomeip_HEAD="; git ls-remote "$vsomeip_Repo" refs/tags/3.4.10 | cut -f1; } | tee -a "$GITHUB_OUTPUT"'

      - name: Cache CMake build artifacts
        id: cache-cmake
        uses: actions/cache@v4
        with:
          key: ${{ env.vsomeip_Cache_PFX }}-${{ steps.vsomeip-head.outputs.vsomeip_HEAD }}
          path: |
            ~/.cmake

      - name: Install Cmake and Ninja
        if: ${{ steps.cache-cmake.outputs.cache-hit != 'true' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build
          
      - name: Install Boost 1.84.0
        if: ${{ steps.cache-cmake.outputs.cache-hit != 'true' }}
        run: |
          wget https://boostorg.jfrog.io/artifactory/main/release/1.84.0/source/boost_1_84_0.tar.gz
          tar xzf boost_1_84_0.tar.gz
          cd boost_1_84_0
          ./bootstrap.sh --prefix=/usr/local
          ./b2
          sudo ./b2 install

      - name: Clone vsomeip repo
        if: ${{ steps.cache-cmake.outputs.cache-hit != 'true' }}
        shell: bash
        env:
          vsomeip_HEAD: ${{ steps.vsomeip-head.outputs.vsomeip_HEAD }}
        run: |
          git clone "$vsomeip_Repo"
          cd vsomeip && git checkout ${{ env.vsomeip_Tag }}
          git submodule update --init --recursive

      - name: Build vsomeip with Cmake
        if: ${{ steps.cache-cmake.outputs.cache-hit != 'true' }}
        shell: bash
        run: |
          cd vsomeip
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/ -G Ninja ..
          ninja

      - name: Install vsomeip
        if: ${{ steps.cache-cmake.outputs.cache-hit != 'true' }}
        run: |
          cd vsomeip/build
          sudo ninja install
          
      - name: Copy vsomeip libraries and headers
        run: |
          mkdir -p ${{ github.workspace }}/vsomeip
          cp /usr/local/lib/libvsomeip*.so* ${{ github.workspace }}/vsomeip
          cp -r /usr/local/include/vsomeip ${{ github.workspace }}/vsomeip

  build-up-client-vsomeip-cpp:
    name: Build up-client-vsomeip-cpp
    needs: [ build-up-cpp, build-vsomeip ]
    runs-on: ubuntu-latest
    env:
      UP_CPP_Cache: ${{ needs.build-up-cpp.outputs.UP_CPP_Cache }}

    steps:
      # Note: will never update here since it will always match from previous job
      - name: Get cached up-cpp conan artifacts
        uses: actions/cache@v4
        with:
          key: ${{ env.UP_CPP_Cache }}
          path: |
            ~/.conan2

      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - uses: actions/checkout@v2
      
      - name: Set LOCAL_VSOMEIP_PATH
        run: echo "LOCAL_VSOMEIP_PATH=${{ github.workspace }}/vsomeip" >> $GITHUB_ENV

      - name: Build and install up-client-vsomeip-cpp
        shell: bash
        run: |
          export CMAKE_PREFIX_PATH="$HOME/local"
          export CMAKE_ZENOH_INCLUDE_PATH="$HOME/local/include"
          sed -i 's/# self.requires("vsomeip\/3.4.10")/self.requires("vsomeip\/3.4.10")#/' conanfile.py
          mkdir build
          cd build
          conan install ../ --build=missing
          cmake -S .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON -DCMAKE_INSTALL_PREFIX=~/local
          cmake --build .

  # NOTE: In GitHub repository settings, the "Require status checks to pass
  # before merging" branch protection rule ensures that commits are only merged
  # from branches where specific status checks have passed. These checks are
  # specified manually as a list of workflow job names. Thus we use this extra
  # job to signal whether all CI checks have passed.
  ci:
    name: CI status checks
    runs-on: ubuntu-latest
    needs: [ build-up-cpp, build-up-client-vsomeip-cpp ]
    if: always()
    steps:
      - name: Check whether all jobs pass
        run: echo '${{ toJson(needs) }}' | jq -e 'all(.result == "success")'
